import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/organisms/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "@/components/providers/ReduxProvider";
import ReduxDebug from "@/components/providers/ReduxDebug";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
  fallback: ["system-ui", "arial"],
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${plusJakartaSans.variable} antialiased`}
        >
          <ReduxProvider>
            <Navbar />
            {children}
            <ReduxDebug />
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
